name: Build iOS App For Sideloading

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore All MAUI Workloads
        run: sudo dotnet workload restore

      - name: Build App Bundle
        run: dotnet publish -f net8.0-ios -c Release -p:EnableCodeSigning=false -p:CheckEolWorkloads=false

      - name: Convert to IPA Archive
        run: |
          mkdir Payload
          find bin/Release/net8.0-ios -name "*.app" -exec cp -r {} ./Payload/ \;
          zip -r MyMapApp.ipa Payload

      - name: Save IPA File
        uses: actions/upload-artifact@v4
        with:
          name: ready-to-sideload
          path: MyMapApp.ipa
