name: Build iOS App For Sideloading

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Pin to .NET 9 SDK
        run: |
          echo '{"sdk":{"version":"9.0.100","rollForward":"latestMinor"}}' > global.json
          cat global.json

      - name: Install Mobile Workloads Globally
        run: sudo dotnet workload install maui-ios maui-android maccatalyst --skip-manifest-update

      - name: Build App Bundle
        run: |
          PROJ=$(find . -name "*.csproj" -print -quit)
          dotnet publish "$PROJ" -f net8.0-ios -c Release -p:EnableCodeSigning=false

      - name: Convert to IPA Archive
        run: |
          mkdir Payload
          APP_PATH=$(find . -name "*.app" -path "*/bin/Release/*" -print -quit)
          echo "Found compiled app bundle at: $APP_PATH"
          cp -r "$APP_PATH" ./Payload/
          zip -r MyMapApp.ipa Payload

      - name: Save IPA File
        uses: actions/upload-artifact@v4
        with:
          name: ready-to-sideload
          path: MyMapApp.ipa
